### ISSUE TITLE
How to generate AMB access token

### ISSUE THREAD

**Issue by SabarishT** [ambrosus/ambrosus-node#392]
I am new to AMB Blockchain. I have to create and store assests and events for my project. Now I am strucking at creating AMB Token to hit API. could anybody please explain how to create signature in detail. 
OR any references will very helpful

**Comment by cehali** [comment]
Hi,
Creating AMB token is described in the documentation: https://ambrosus.docs.apiary.io/#introduction/group-token-[token]. Also, you can use JS-SDK (https://github.com/ambrosus/sdk-javascript), where helper function is implemented (https://github.com/ambrosus/sdk-javascript/blob/dev/src/index.js#L153)

**Comment by SabarishT** [comment]
Thank you @cehali for your reply. Is there any libraries related to JAVA.

**Comment by cehali** [comment]
https://github.com/ambrosus/sdk-java

**Comment by SabarishT** [comment]
![Screenshot3](https://user-images.githubusercontent.com/29983995/60889758-691fa400-a277-11e9-96ea-f8566010074d.png)

sdk-java dependency is not working. I have tried in Eclipse Gradle and also Android Studio Gradle.
I think settings.gradle is missing. Kindly help regarding this issue. I have shared screenshot which I got.

**Comment by cehali** [comment]
Please create an issue in Java SDK. A person responsible will take look at it.  Meanwhile, you can try generating a token via API.

**Comment by SabarishT** [comment]
Okay @cehali. I have tried with Javascript-SDK also. Using Javascript-SDK I got something like 

`eyJpZERhdGEiOnsiY3JlYXRlZEJ5IjoiMHg5YzZENmI3MjQ0MzI0NzE4NDNFMmUwNEQzYjUwMjgyNThlNkE0YUYwIiwidmFsaWRVbnRpbCI6MTU2MjkzMzg3Mn0sInNpZ25hdHVyZSI6IjB4ODg2Mjg5YWRjYzEzNmQ5YjA1MDFiNDg0YzYxYWExOWZhNzg2OWE0Mzk0ZGU3MzFhOGE5YjhmMzM1OGFkNzcwODVjZDI5NmViZWFlNmViOGY0NTRiYmY1ZDg4OGIwZmJmZDgzNjMyOTZjZjNkNTkyYWZlMTczYWZmNjM5N2RkZWQxYiJ9`

I have passed parameters **secret** as my ethereum address private key and **timestamp** as tomorrow's timestamp.

With above token to the API is not accepting. I got something like below while hitting **Add account API** using postman.
**URL** : https://hermes.ambrosus-test.com/accounts
`{
    "reason": "Permission denied: Account with address 0x9c6D6b724432471843E2e04D3b5028258e6A4aF0 doesn't exist"
}`

Actually what exact values I have to pass to following method:
getApiToken("C6BCE9F7BDC5198514BF4D286C90CED4A8JNAYTIKEO94LD5B96531DAF2EA2C91",1562933872))
Please help me. Thank you

**Comment by SabarishT** [comment]
For Authorization, while hitting the following API with my ethereum private key
**URL** : https://hermes.ambrosus-test.com/token
**Headers**: 
Authorization: AMB <<**My ethereum private key**>>
Content-Type: application/json
**RequestBody**:
{
    "validUntil": 1562933872
}
**Response**:
{
    "reason": "Permission denied: Authorization by secret key is not possible"
}

I am getting above response for **Token API**. Can you please tell me What I have to provide in place of **My ethereum private key**. Kindly suggest me. I am strucking here almost a week.

**Comment by krzysztof-jelski** [comment]
Authorization by secret key is disable on test and production. You need to generate the AMB access token client-side.

**Comment by krzysztof-jelski** [comment]
> 
> Actually what exact values I have to pass to following method:
> getApiToken("C6BCE9F7BDC5198514BF4D286C90CED4A8JNAYTIKEO94LD5B96531DAF2EA2C91",1562933872))

The secret key you need to pass is the one corresponding to your public address, which is `0x2EEBB6D3CE345149a6ADBdebf88E59D4f26c446b` as I've seen in https://github.com/ambrosus/ambrosus-node/issues/394#issue-469712079.

The timestamp needs to be in the future.

**Comment by krzysztof-jelski** [comment]
In the future please use tech [at ] ambrosus.com for support.
