### ISSUE TITLE
API Access Issue

### ISSUE THREAD

**Issue by SabarishT** [ambrosus/ambrosus-node#394]
I am getting "**Permission denied: Authorization by secret key is not possible**" for following API’s
 
**1. GENERATE TOKEN API
2. CREATE ASSET API
3. CREATE EVENT API**
 
Please find below My **Ambrosus Developer Account** and it’s **Permissions**:
 
{
    "address": "0x2EEBB6D3CE345149a6ADBdebf88E59D4f26c446b",
    "accessLevel": 1,
    "organization": 684,
    "permissions": [
        "create_asset",
        "create_event",
        "manage_accounts"
    ],
    "registeredBy": "0x7C6253525fEe9CdF10047B07866E0E1b3Dffdc65",
    "registeredOn": 1563366213
}
 
As per above information, I am having permission to create_asset, create_event. 
Actually I am using **POSTMAN** to use the **API**’s. And My Request as follows
 
**URL**: https://hermes.ambrosus-test.com/assets
**Headers**: 
Content-Type: application/json
Authorization: AMB <<My account secret key>>
**Request**:
{
    "content": {
        "idData": {
            "createdBy": "0x5f01d1318d88868d46c77c090543f3a3224f7bf1",
            "timestamp": 1503424923,
            "sequenceNumber": 0
        }
    }
}
**Response**:
{
    "reason": "Permission denied: Authorization by secret key is not possible"
}
 
So could anyone please help me regarding How to give request and what type of Authorization I have to provide for **GENERATE TOKEN API,CREATE ASSET API, CREATE EVENT API.**

**Comment by krzysztof-jelski** [comment]
Authorization by secret key is disable on test and production. You need to generate the AMB access token client-side.

**Comment by krzysztof-jelski** [comment]
Closing, as there is no issue with the code itself. In the future please use tech [at ]ambrosus.com for support questions.
