### ISSUE TITLE
Node Metrics Page - Lots 404 status

### ISSUE THREAD

**Issue by shipmonite** [ambrosus/ambrosus-node#428]
Check any nodes url metrics page

`http://[node URL]/metrics`

Scroll to the bottom, and there's a lot of "404 status" count. Something seems to be broken and may need to be investigated/fixed.

**Comment by vpowler** [comment]
The Internet is full of bots and crawlers. These automated software fetch many different pages which don't exist on the server (node). That is why there are so many 404 errors.

You can view the logs by running the following command:
docker logs CONTAINER_ID

You can obtain container ID by running the following command:
docker ps
